# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='created_time',
        ),
    ]
